///////////////////////////////////////////////////////////
//  CompteBancaire.cs
//  Implementation of the Class CompteBancaire
//  Generated by Enterprise Architect
//  Created on:      30-juin-2021 16:56:13
//  Original author: Us10
///////////////////////////////////////////////////////////




public class CompteBancaire {

	private double decouvertAutorise;
	private string nomcli;
	private long numcpt;
	private double solde;

	public CompteBancaire(){

	}

	~CompteBancaire(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="montant"></param>
	public static void crediter(double montant){

	}

	/// 
	/// <param name="ok"></param>
	/// <param name="montant"></param>
	public void debiter(boolean ok, double montant){

	}

}//end CompteBancaire